### ISSUE TITLE
Updating translations

### ISSUE THREAD

**Issue by brunelli** [brunelli/tbsm#1]
We should implement a `make translations` command to update references on the template file and then update the translation files.

This is a better workflow than use the hacky script I wrote + poedit.

**Comment by loh-tar** [comment]
I have no clue how translation stuff is handled by other projects.

A `make translations` command/option is somehow independent from the main problem how to keep tbsm-source and the translation files in sync.

Such make command can only assist to keep things simple, which tool is called by `make` is the question to answer.

poedit has some dependencies I would like avoid when there is an other tool available todo what is needed.

With that, I think we (me) need to know "what is needed" at all, then we can decide which tool is appropriate.

**Comment by brunelli** [comment]
In Arch, the package is called `gettext`. It provides lots of commands, one of them being the `msgfmt` command (which is currently being used in the Makefile to compile translations).

What we need is something (`bash --dump-po-strings`?) to update the references and then `msgmerge` to [update the PO files](http://punt.sourceforge.net/gettext/gettext_6.html).

I also should take a look at `gettextize`.

**Comment by brunelli** [comment]
e278367 implements a `make update-po` command.

There are 4 things we do there:

1. Clean the pot file leaving only the header (sed);

2. Dump translatable strings, appending them to the end of the pot file (bash);

3. Remove duplicate strings (msguniq);

4. Update all po files (msgmerge).

I think this is ready to be documented.
