### ISSUE TITLE
Check for tty when running from quick menu

### ISSUE THREAD

**Issue by brunelli** [brunelli/tbsm#6]
Running a session from quick menu from a already running session is allowed. From the normal menu it is not.

-----

Certainly out-of-scope for the i18n PR, but I'm opening this just so I don't forget to look into it later.

**Comment by loh-tar** [comment]
Oops! 

> ..so I don't forget to look into it later.

Thanks!

**Comment by brunelli** [comment]
> Running a session from quick menu from a already running session is allowed.

It actually isn't. I don't know why I thought it was.
